import React from "react";
import Banner from "../../components/Banner";

const TermsAndConditions = () => {
  return (
    <div className="w-full bg-white  lg:pb-[100px] ">
        <Banner
                title="Terms & Conditions"
                subtitle="Learn more about our company"
                breadcrumb={[
                  { label: "Home", href: "/" },
                  { label: "Terms & Conditions", href: "/terms&conditions" },
                ]}
              />
      <div className="container mx-auto p-6 bg-white shadow ">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Terms & Conditions
          </h1>
          <div className="h-1 w-24 bg-blue-600 rounded"></div>
        </div>

        <div className="space-y-6 text-gray-700 leading-relaxed">
          <section className="bg-gray-50 p-6 rounded-lg">
            <p className="text-sm">
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules thereunder as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </p>
          </section>

          <section>
            <p>
              This document is published in accordance with the provisions of
              Rule 3 (1) of the Information Technology (Intermediaries
              guidelines) Rules, 2011 that require publishing the rules and
              regulations, privacy policy and Terms of Use for access or usage
              of domain name{" "}
              <a
                href="https://www.digitalnawab.com"
                className="!text-blue-600 hover:text-blue-800 underline"
              >
                https://www.digitalnawab.com
              </a>{" "}
              ('Website'), including the related mobile site and mobile
              application (hereinafter referred to as 'Platform').
            </p>
          </section>

          <section className="bg-blue-50 p-6 rounded-lg border-l-4 border-blue-600">
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              Platform Owner
            </h2>
            <p>
              The Platform is owned by{" "}
              <span className="font-semibold">
                TRAFICO ANALYTICA PRIVATE LIMITED
              </span>
              , a company incorporated under the Companies Act, 1956 with its
              registered office at B12 A, L Rd, Mahanagar, Lucknow, Uttar
              Pradesh 226006 (hereinafter referred to as 'Platform Owner', 'we',
              'us', 'our').
            </p>
          </section>

          <section>
            <p>
              Your use of the Platform and services and tools are governed by
              the following terms and conditions ("Terms of Use") as applicable
              to the Platform including the applicable policies which are
              incorporated herein by way of reference. If You transact on the
              Platform, You shall be subject to the policies that are applicable
              to the Platform for such transaction.
            </p>
          </section>

          <section>
            <p>
              By mere use of the Platform, You shall be contracting with the
              Platform Owner and these terms and conditions including the
              policies constitute Your binding obligations with Platform Owner.
              These Terms of Use relate to your use of our website, goods (as
              applicable) or services (as applicable) (collectively,
              'Services').
            </p>
          </section>

          <section className="bg-yellow-50 p-6 rounded-lg border-l-4 border-yellow-500">
            <div className="flex items-start">
              <div className="flex-shrink-0">
                <svg
                  className="h-5 w-5 text-yellow-400 mt-0.5"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
                    clipRule="evenodd"
                  />
                </svg>
              </div>
              <div className="ml-3">
                <h3 className="text-sm font-medium text-yellow-800">
                  Important Notice
                </h3>
                <p className="mt-1 text-sm text-yellow-700">
                  Any terms and conditions proposed by You which are in addition
                  to or which conflict with these Terms of Use are expressly
                  rejected by the Platform Owner and shall be of no force or
                  effect. These Terms of Use can be modified at any time without
                  assigning any reason. It is your responsibility to
                  periodically review these Terms of Use to stay informed of
                  updates.
                </p>
              </div>
            </div>
          </section>

          <section>
            <p>
              For the purpose of these Terms of Use, wherever the context so
              requires 'you', 'your' or 'user' shall mean any natural or legal
              person who has agreed to become a user/buyer on the Platform.
            </p>
          </section>

          <section className="bg-red-50 p-6 rounded-lg border-l-4 border-red-500">
            <div className="flex items-start">
              <div className="flex-shrink-0">
                <svg
                  className="h-5 w-5 text-red-400 mt-0.5"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                    clipRule="evenodd"
                  />
                </svg>
              </div>
              <div className="ml-3">
                <h3 className="text-sm font-medium text-red-800">
                  Agreement Required
                </h3>
                <p className="mt-1 text-sm text-red-700 font-medium">
                  ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES
                  YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE
                  TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE
                  PROCEEDING.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Terms of Use
            </h2>
            <p className="mb-4">
              The use of Platform and/or availing of our Services is subject to
              the following Terms of Use:
            </p>

            <div className="space-y-4">
              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  1
                </span>
                <p>
                  To access and use the Services, you agree to provide true,
                  accurate and complete information to us during and after
                  registration, and you shall be responsible for all acts done
                  through the use of your registered account on the Platform.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  2
                </span>
                <p>
                  Neither we nor any third parties provide any warranty or
                  guarantee as to the accuracy, timeliness, performance,
                  completeness or suitability of the information and materials
                  offered on this website or through the Services, for any
                  specific purpose. You acknowledge that such information and
                  materials may contain inaccuracies or errors and we expressly
                  exclude liability for any such inaccuracies or errors to the
                  fullest extent permitted by law.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  3
                </span>
                <p>
                  Your use of our Services and the Platform is solely and
                  entirely at your own risk and discretion for which we shall
                  not be liable to you in any manner. You are required to
                  independently assess and ensure that the Services meet your
                  requirements.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  4
                </span>
                <p>
                  The contents of the Platform and the Services are proprietary
                  to us and are licensed to us. You will not have any authority
                  to claim any intellectual property rights, title, or interest
                  in its contents. The contents includes and is not limited to
                  the design, layout, look and graphics.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  5
                </span>
                <p>
                  You acknowledge that unauthorized use of the Platform and/or
                  the Services may lead to action against you as per these Terms
                  of Use and/or applicable laws.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  6
                </span>
                <p>
                  You agree to pay us the charges associated with availing the
                  Services.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  7
                </span>
                <p>
                  You agree not to use the Platform and/ or Services for any
                  purpose that is unlawful, illegal or forbidden by these Terms,
                  or Indian or local laws that might apply to you.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  8
                </span>
                <p>
                  You agree and acknowledge that website and the Services may
                  contain links to other third party websites. On accessing
                  these links, you will be governed by the terms of use, privacy
                  policy and such other policies of such third party websites.
                  These links are provided for your convenience to provide
                  further information.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  9
                </span>
                <p>
                  You understand that upon initiating a transaction for availing
                  the Services you are entering into a legally binding and
                  enforceable contract with the Platform Owner for the Services.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  10
                </span>
                <p>
                  You shall indemnify and hold harmless Platform Owner, its
                  affiliates, group companies (as applicable) and their
                  respective officers, directors, agents, and employees, from
                  any claim or demand, or actions including reasonable
                  attorney's fees, made by any third party or penalty imposed
                  due to or arising out of Your breach of this Terms of Use,
                  Privacy Policy and other Policies, or Your violation of any
                  law, rules or regulations or the rights (including
                  infringement of intellectual property rights) of a third
                  party.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  11
                </span>
                <p>
                  Notwithstanding anything contained in these Terms of Use, the
                  parties shall not be liable for any failure to perform an
                  obligation under these Terms if performance is prevented or
                  delayed by a force majeure event.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  12
                </span>
                <p>
                  These Terms and any dispute or claim relating to it, or its
                  enforceability, shall be governed by and construed in
                  accordance with the laws of India.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  13
                </span>
                <p>
                  All disputes arising out of or in connection with these Terms
                  shall be subject to the exclusive jurisdiction of the courts
                  in Lucknow and Uttar Pradesh.
                </p>
              </div>

              <div className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-medium mr-3 mt-0.5">
                  14
                </span>
                <p>
                  All concerns or communications relating to these Terms must be
                  communicated to us using the contact information provided on
                  this website.
                </p>
              </div>
            </div>
          </section>

          <section className="bg-gray-100 p-6 rounded-lg mt-8">
            <div className="text-center">
              <p className="text-sm text-gray-600">
                Last updated: {new Date().toLocaleDateString()}
              </p>
              <p className="text-sm text-gray-600 mt-2">
                For questions about these Terms & Conditions, please contact us
                through our website.
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
